# Generated by Django 4.0.4 on 2022-05-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('camp_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID лагеря')),
                ('name', models.CharField(max_length=255, verbose_name='Название лагеря')),
                ('geography', models.TextField(verbose_name='Расположение лагеря')),
            ],
            options={
                'verbose_name': 'Лагерь',
                'verbose_name_plural': 'Лагеря',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id',
                 models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID инструктора')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО инструктора')),
                ('experience', models.IntegerField(verbose_name='Опыт работы инструктора')),
            ],
            options={
                'verbose_name': 'Инструктор',
                'verbose_name_plural': 'Инструктора',
            },
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('tourist_id',
                 models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID туриста')),
                ('i_name', models.CharField(max_length=255, verbose_name='Имя туриста')),
                ('f_name', models.CharField(max_length=255, verbose_name='Фамилия туриста')),
                ('o_name', models.CharField(max_length=255, verbose_name='Отчество туриста')),
                ('birth', models.DateField(max_length=255, verbose_name='Дата рождения туриста')),
                ('camp_id', models.ForeignKey(on_delete=models.SET(-1), to='Tourism.camp', verbose_name='ID лагеря')),
                ('instructor_id',
                 models.ForeignKey(on_delete=models.SET(-1), to='Tourism.instructor', verbose_name='ID инструктора')),
            ],
            options={
                'verbose_name': 'Турист',
                'verbose_name_plural': 'Туристы',
            },
        ),
    ]
